### ISSUE TITLE
Fail to install crypto library

### ISSUE THREAD

**Issue by Tequilac** [CloudPyRDF/CERNLogin#1]
## Steps to reproduce:
Getting docker container:
1. Docker image pulled from `burooo/clientello:issue`
2. Docker container started with `docker run --name <name> -dp 8888:8888 -it <image-id> bash`
Environment inside docker container:
npm version 6.14.15
node version 14.18.1
jupyter lab version 3.2.4
Running commands:
1. `git clone https://github.com/CloudPyRDF/CERNLogin.git`
2. `cd CERNLogin/`
3. `./install.sh` - this script contains the following commands:
```
#!/usr/bin/env bash
set -e

jlpm
jlpm build
jupyter labextension install .
jlpm build
jupyter lab build

python3 -m pip install jupyter_server
python3 -m pip install -e .
jupyter serverextension enable CERNLogin
```
The script succeeds with no errors.
Running the jupyter lab:
`jupyter lab --allow-root --ip=0.0.0.0`
It claims that
`CERNLogin | extension was successfully linked.`
and
`CERNLogin | extension was successfully loaded.`
Opening the `http://127.0.0.1:8888/lab?token=<token-id>` page in the browser
Console output:
![image](https://user-images.githubusercontent.com/58514571/143779056-ea6b2775-4200-4b30-8221-5ae5ff408e8f.png)

**Comment by Tequilac** [comment]
@ajbozarth

**Comment by Kamilbur** [comment]
clientello image contains ROOT framework and other stuff we need
> 1. Docker image pulled from `burooo/clientello:issue`

but we rulled out other dependencies as a potential source of an issue.
I tried with different docker image build upon ubuntu:20.04 and it does not work either.
I add a Dockerfile with environment below:
```dockerfile
FROM ubuntu:20.04

# install python
RUN apt-get update && \
    apt-get install -y python3 python3-pip curl git

#install jupyterlab
RUN python3 -m pip install jupyterlab

ARG NODE_VER=14.18.1

#install node
RUN curl https://nodejs.org/dist/v${NODE_VER}/node-v${NODE_VER}-linux-x64.tar.xz -o node-v${NODE_VER}-linux-x64.tar.xz && \
    tar -xf node-v${NODE_VER}-linux-x64.tar.xz -C /usr/lib && \
    rm node-v${NODE_VER}-linux-x64.tar.xz && \
    ln -sf /usr/lib/node-v${NODE_VER}-linux-x64/bin/node /usr/bin/node && \
    ln -sf /usr/lib/node-v${NODE_VER}-linux-x64/bin/npm /usr/bin/

CMD ["/usr/bin/bash"]
```
